INSERT INTO `equip431_impacto`.`categoria` 
            (`id`, 
             `super`, 
             `nome`, 
             `imagem`, 
             `descricao`, 
             `ativo`, 
             `data_cadastro`) 
VALUES      ( NULL, 
              NULL, 
              'Arte & Design', 
              NULL, 
              'Cursos de Arte e Design', 
              'S', 
              CURRENT_TIMESTAMP ), 
            ( NULL, 
              NULL, 
              'Desenvolvimento', 
              NULL, 
              'Cursos nas mais diversas tecnologias de desenvolvimento de softwares.', 
              'S', 
              CURRENT_TIMESTAMP ), 
            ( NULL, 
              NULL, 
              'Redes', 
              NULL, 
              'Cursos de capacitação na manutenção e desenvolvimento de redes.', 
              'S', 
              CURRENT_TIMESTAMP ), 
            ( NULL, 
              NULL, 
              'Office', 
              NULL, 
              'Cursos de capacitação em ferramentas do pacote Office 2013.', 
              'S', 
              CURRENT_TIMESTAMP ), 
            ( NULL, 
              NULL, 
              'Planejamento & Gestão', 
              NULL, 
              'Cursos de capacitação para gestores de equipes de desenvolvimento.', 
              'S', 
              CURRENT_TIMESTAMP ); 